import {StyleSheet} from 'react-native';
import {ScreenHeight} from '../../common/Constance';
import CustomColors from '../../asset/colors';

const styles = StyleSheet.create({
  heading: {
    color: CustomColors.black,
    fontSize: 16,
    fontWeight: '800',
    padding: 5,
    fontFamily: "'Poppins-Bold",
  },
  tileReminder: {
    backgroundColor: CustomColors.seaBlue,
    height: 170,
    flex: 1,
    borderRadius: 15,
    paddingHorizontal: 20,
    marginBottom: 29,
    justifyContent: 'center',
    alignItems: 'center',
  },
  horizontalLine: {
    borderBottomColor: CustomColors.grey,
    borderBottomWidth: 1,
  },
  reminderText: {
    color: CustomColors.black,
    fontSize: 18,
    fontWeight: '800',
    fontFamily: "'Poppins-Bold",
  },
  messageIcon: {
    width: 22,
    height: 22,
    tintColor: CustomColors.Secondary,
  },
  indiaText: {
    bottom: 10,
    left: 40,
    color: CustomColors.black,
  },
  messageScreen: {
    position: 'absolute',
    height: 50,
    width: 50,
    borderRadius: 25,
    right: 15,
    shadowOffset: {height: 0, width: 3},
    shadowRadius: 4,
    bottom: 50,
    backgroundColor: CustomColors.PrimaryBlue,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
  },
  modal: {
    // bottom: 0,
    position: 'absolute',
    margin: 0,
    width: '100%',
    maxHeight: '99%',
  },
  overLay: {
    borderTopRightRadius: 7,
    borderTopLeftRadius: 7,
    backgroundColor: CustomColors.Secondary,
    // paddingBottom: 25,
    height: ScreenHeight / 1.3,
  },
  innerLay: {
    paddingHorizontal: 20,
    height: 100,
    paddingVertical: 20,
  },
  chatLay: {
    backgroundColor: CustomColors.lightBlue,
    // height: ScreenHeight / 1.5,
    // bottom: 10,
    height: '100%',
    paddingBottom: 60,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    borderWidth: 2,
    borderColor: CustomColors.lightBlue,
  },
  loginTextBox: {
    borderWidth: 1,
    borderColor: CustomColors.lightGrey,
    height: 49,
    borderRadius: 10,
    paddingHorizontal: 15,
    // width: '80%',
    backgroundColor: CustomColors.Secondary,
  },
  input: {
    height: 40,
    width: '100%',
    borderColor: CustomColors.lightGrey,
    paddingLeft: 10,
    borderRadius: 10,
  },
  searchBarConatiner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: CustomColors.lightGrey,
    borderWidth: 1,
    height: 40,
    width: '100%',
    borderRadius: 10,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  aware: {
    flexGrow: 1,
  },
  userResponseContainerMain: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  botResponseContainerMain: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  chatLayResponseContainer: {
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  userResponseContainer: {
    // width: ScreenWidth,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderTopStartRadius: 50,
    borderBottomStartRadius: 50,
    borderTopEndRadius: 25,
    backgroundColor: CustomColors.PrimaryBlue,
  },
  botResponseContainer: {
    // width: (ScreenWidth - 40) / 2 + 20,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderTopEndRadius: 50,
    borderBottomEndRadius: 50,
    borderTopStartRadius: 25,
    backgroundColor: CustomColors.Secondary,
  },
  messageText: {
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '400',
    paddingVertical:5,
  },
  ResponseTypeText: {
    fontSize: 16,
    lineHeight: 18,
    fontWeight: '600',
  },
  closeIcon: {
    tintColor: CustomColors.PrimaryColor,
    width: 15,
    height: 15,
  },
  textBoxContainer: {
    // bottom: 35,
    position: 'absolute',
    paddingHorizontal: 20,
    margin: 0,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CustomColors.Secondary,
    height: ScreenHeight / 10,
    justifyContent: 'center',
  },
  headerContainer: {
    height: 50,
    backgroundColor: CustomColors.Secondary,
    borderRadius: 30,
    borderColor: CustomColors.lightGrey,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  headerContainerMain: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
  },
  hotel: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderTopEndRadius: 50,
    borderBottomEndRadius: 50,
    borderTopStartRadius: 25,
    backgroundColor: CustomColors.Secondary,
    // flexDirection: 'row',
    // alignItems: 'center',
  },
  responseTypeHeader: {
    backgroundColor: CustomColors.PrimaryBlue,
    borderRadius: 20,
    paddingHorizontal: 50,
    paddingVertical: 10,
    marginBottom: 10,
  },
  listContainer: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: CustomColors.Secondary,
    marginHorizontal: 10,
    marginVertical: 10,
  },
  confirmButton: {
    textAlign: 'center',
    color: CustomColors.Secondary,
    fontSize: 18,
    fontWeight: '600',
  },
  confirmButtonContainer: {
    borderRadius: 5,
    backgroundColor: CustomColors.PrimaryBlue,
    height: 39,
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomTextBox: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: 40,
    borderColor: CustomColors.grey,
    borderWidth: 1,
    paddingHorizontal: 10,
  },
  renderItemContainer: {
    backgroundColor: CustomColors.Secondary,
    borderRadius: 5,
    marginBottom: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderColor: CustomColors.grey,
    borderWidth: 1,
  },
  roboIcon:{
    width: 50, 
    height: 50
  },
  scrollView:{
    flex:1,
    backgroundColor: CustomColors.lightBlue,
  },
  sendIcon:{
    width: 30, 
    height: 30, 
    tintColor: CustomColors.PrimaryBlue
  },
  sendIconContainer:{
    backgroundColor: CustomColors.Secondary, 
    marginLeft: 20
  },
  optionsListContainer:{
    marginRight: 8,
     backgroundColor: CustomColors.seaBlue,
  }
});

export default styles;
